### ISSUE TITLE
Compatibility with displays without a chip select pin

### ISSUE THREAD

**Issue by james1236** [adafruit/Adafruit-Mini-PiTFT-240x135-TFT-PCB#1]
Could this be modified to allow compatibility with these kinds of 1.3" TFT displays that have no chip select pin?

https://uk.banggood.com/1_3-Inch-IPS-TFT-LCD-Display-240+240-Color-HD-LCD-Screen-3_3V-ST7789-Driver-Module-p-1383404.html

Thank you

**Comment by ladyada** [comment]
if youre talking about firmware, no - the lack of CS causes the SPI mode to be different
